version: "3.8"

###############################################################################
#  reverse-proxy (optional – remove this block if you don’t need HTTPS)
###############################################################################
services:
  nginx:
    image: nginx:1.25.3-bookworm
    container_name: nginx
    restart: unless-stopped
    ports: ["80:80", "443:443"]
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro

  nginx-gen:
    image: btcpayserver/docker-gen:0.10.7
    container_name: nginx-gen
    restart: unless-stopped
    environment:
      DEFAULT_HOST: btcpay-dev2.megalith-node.com
    entrypoint: >
      /usr/local/bin/docker-gen
      -notify-sighup nginx -watch -wait 5s:30s
      /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./Generated/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
    links: [nginx]

  letsencrypt-nginx-proxy-companion:
    image: btcpayserver/letsencrypt-nginx-proxy-companion:2.2.9-2
    container_name: letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx
      ACME_CA_URI: production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
    links: [nginx-gen]

###############################################################################
#  core stack  (bitcoind + NBX + CLN + optional RTL)
###############################################################################
  postgres:
    image: btcpayserver/postgres:13.18
    container_name: generated_postgres_1
    restart: unless-stopped
    shm_size: 256mb
    command: ["-c","random_page_cost=1.0","-c","shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: ["5432:5432"]
    volumes:
      - postgres_datadir:/var/lib/postgresql/data

  bitcoind:
    image: btcpayserver/bitcoin:27.1
    container_name: btcpayserver_bitcoind
    restart: unless-stopped
    environment:
      BITCOIN_NETWORK: mainnet
      CREATE_WALLET: "false"
      BITCOIN_WALLETDIR: /walletdata
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500
        prune=50000
        mempoolfullrbf=1
        rpcauth=btcrpc:a6a5d29a3f44f02e4cd8cabb5b10a234$$ab6152915515f6a9cca806d2ab5f0e2794c346ba74f812c61e48241d523778b8
    expose: ["43782", "39388"]
    volumes:
      # persist the entire ~/.bitcoin directory on the host
      - type: bind
        source: ./data/bitcoin_datadir
        target: /data
      # keep wallets in a (small) named volume – change to a bind-mount if you prefer
      - bitcoin_wallet_datadir:/walletdata

  nbxplorer:
    image: nicolasdorier/nbxplorer:2.5.25
    container_name: generated_nbxplorer_1
    restart: unless-stopped
    ports: ["32838:32838"]
    environment:
      NBXPLORER_NETWORK: mainnet
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorermainnet
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    links: [postgres]
    volumes:
      - type: bind
        source: ./data/nbxplorer_datadir
        target: /datadir
      - type: bind
        source: ./data/bitcoin_datadir
        target: /root/.bitcoin

  clightning_bitcoin:
    image: btcpayserver/lightning:v25.02
    container_name: btcpayserver_clightning_bitcoin
    restart: unless-stopped
    ports: ["9735:9735", "3010:3010", "9736:9736"]
    expose: ["9736"]
    environment:
      LIGHTNINGD_NETWORK: mainnet
      LIGHTNINGD_CHAIN: btc
      LIGHTNINGD_READY_FILE: /root/.nbxplorer/btc_fully_synched
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind
        experimental-offers
        rpc-file-mode=0666
        clnrest-port=3010
        grpc-port=9736
    links: [bitcoind]
    volumes:
      - type: bind
        source: ./data/clightning_bitcoin_datadir
        target: /root/.lightning
      - type: bind
        source: ./data/bitcoin_datadir
        target: /etc/bitcoin
      - type: bind
        source: ./data/nbxplorer_datadir
        target: /root/.nbxplorer

  bitcoin_rtl:
    image: shahanafarooqui/rtl:v0.15.4
    container_name: generated-bitcoin_rtl-1
    restart: unless-stopped
    expose: ["3000"]
    environment:
      LN_IMPLEMENTATION: CLN
      CONFIG_PATH: /root/.lightning/config
      LN_SERVER_URL: http://clightning_bitcoin:3010
      RUNE_PATH: /root/.lightning/rune.env
      RTL_CONFIG_PATH: /data/
      RTL_COOKIE_PATH: /data/.cookie
    labels:
      traefik.enable: "true"
      traefik.http.routers.bitcoin_rtl.rule: Host(`btcpay-dev2.megalith-node.com`) && (Path(`/rtl`) || PathPrefix(`/rtl/`))
    volumes:
      - type: bind
        source: ./data/clightning_bitcoin_datadir
        target: /root/.lightning
      - type: bind
        source: ./data/bitcoin_datadir
        target: /etc/bitcoin
      - clightning_bitcoin_rtl_datadir:/data  # small, leave named

###############################################################################
#  named volumes that stick around
###############################################################################
volumes:
  nginx_conf:
  nginx_vhost:
  nginx_html:
  nginx_certs:
  acme:
  bitcoin_wallet_datadir:
  clightning_bitcoin_rtl_datadir:
  postgres_datadir: