version: "3.8"

services:
  caddy:
    image: caddy:2.7.6
    container_name: caddy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  postgres:
    image: btcpayserver/postgres:13.18
    container_name: generated_postgres_1
    restart: unless-stopped
    shm_size: 256mb
    command: ["-c", "random_page_cost=1.0", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports: ["5432:5432"]
    volumes:
      - postgres_datadir:/var/lib/postgresql/data

  bitcoind:
    image: btcpayserver/bitcoin:27.1
    container_name: btcpayserver_bitcoind
    restart: unless-stopped
    environment:
      BITCOIN_NETWORK: mainnet
      CREATE_WALLET: "false"
      BITCOIN_WALLETDIR: /walletdata
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=1500
        prune=250000
        dbcache=2000
        mempoolfullrbf=1
        rpcauth=btcrpc:a6a5d29a3f44f02e4cd8cabb5b10a234$$ab6152915515f6a9cca806d2ab5f0e2794c346ba74f812c61e48241d523778b8
    expose: ["43782", "39388"]
    volumes:
      - type: bind
        source: ./data/bitcoin_datadir
        target: /home/bitcoin/.bitcoin
      - bitcoin_wallet_datadir:/walletdata

  nbxplorer:
    image: nicolasdorier/nbxplorer:2.5.25
    container_name: generated_nbxplorer_1
    restart: unless-stopped
    ports: ["32838:32838"]
    environment:
      NBXPLORER_NETWORK: mainnet
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorermainnet
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    links: [postgres]
    volumes:
      - type: bind
        source: ./data/nbxplorer_datadir
        target: /datadir
      - type: bind
        source: ./data/bitcoin_datadir
        target: /root/.bitcoin
    depends_on:
      - bitcoind
      - postgres

  clightning_bitcoin:
    image: btcpayserver/lightning:v25.02
    container_name: btcpayserver_clightning_bitcoin
    restart: unless-stopped
    ports: ["9735:9735", "3010:3010", "9736:9736"]
    expose: ["9736"]
    environment:
      LIGHTNINGD_NETWORK: mainnet
      LIGHTNINGD_CHAIN: btc
      LIGHTNINGD_READY_FILE: /root/.nbxplorer/btc_fully_synched
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind
        experimental-offers
        rpc-file-mode=0666
        clnrest-port=3010
        grpc-port=9736
        announce-addr=64.23.239.207:9735  
    links: [bitcoind]
    volumes:
      - type: bind
        source: ./data/clightning_bitcoin_datadir
        target: /root/.lightning
      - type: bind
        source: ./data/bitcoin_datadir
        target: /etc/bitcoin
      - type: bind
        source: ./data/nbxplorer_datadir
        target: /root/.nbxplorer

  bitcoin_rtl:
    image: shahanafarooqui/rtl:v0.15.4
    container_name: generated-bitcoin_rtl-1
    restart: unless-stopped
    expose: ["3000"]
    environment:
      LN_IMPLEMENTATION: CLN
      CONFIG_PATH: /root/.lightning/config
      LN_SERVER_URL: http://clightning_bitcoin:3010
      RUNE_PATH: /root/.lightning/rune.env
      RTL_CONFIG_PATH: /data/
      RTL_COOKIE_PATH: /data/.cookie
    volumes:
      - type: bind
        source: ./data/clightning_bitcoin_datadir
        target: /root/.lightning
      - type: bind
        source: ./data/bitcoin_datadir
        target: /etc/bitcoin
      - clightning_bitcoin_rtl_datadir:/data

volumes:
  caddy_data:
  caddy_config:
  bitcoin_wallet_datadir:
  clightning_bitcoin_rtl_datadir:
  postgres_datadir: