version: "3"
services:
  btcpayserver:
    restart: unless-stopped
    container_name: generated_btcpayserver_1
    image: ${BTCPAY_IMAGE:-btcpayserver/btcpayserver:2.1.1}
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_EXPLORERPOSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;MaxPoolSize=80;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: "root@host.docker.internal"
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_SSHAUTHORIZEDKEYS: ${BTCPAY_SSHAUTHORIZEDKEYS}
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_UPDATEURL: https://api.github.com/repos/btcpayserver/btcpayserver/releases/latest
      BTCPAY_DOCKERDEPLOYMENT: "true"
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "type=clightning;server=unix://etc/clightning_bitcoin/lightning-rpc"
      BTCPAY_BTCEXTERNALRTL: "server=/rtl/api/authenticate/cookie;cookiefile=/etc/clightning_bitcoin_rtl/.cookie"
      HIDDENSERVICE_NAME: BTCPayServer
      HIDDENSERVICE_REVERSEPROXY: nginx
      BTCPAY_TORRCFILE: /usr/local/etc/tor/torrc-2
      BTCPAY_SOCKSENDPOINT: tor:9050
    labels:
      traefik.enable: "true"
      traefik.http.routers.btcpayserver.rule: Host(`${BTCPAY_HOST}`)
    links:
    - postgres
    - clightning_bitcoin
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "btcpay_pluginsdir:/root/.btcpayserver/Plugins"
    - "clightning_bitcoin_datadir:/etc/clightning_bitcoin"
    - "clightning_bitcoin_rtl_datadir:/etc/clightning_bitcoin_rtl"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
    - "tor_torrcdir:/usr/local/etc/tor/"
    ports:
    - "${NOREVERSEPROXY_HTTP_PORT:-80}:49392"
  bitcoind:
    restart: unless-stopped
    container_name: btcpayserver_bitcoind
    image: btcpayserver/bitcoin:27.1
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      CREATE_WALLET: "false"
      BITCOIN_WALLETDIR: "/walletdata"
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500

        prune=50000
        mempoolfullrbf=1
        onion=tor:9050
        # rpcuser=btcrpc
        # rpcpassword=btcpayserver4ever
        # We need to use rpcauth because we also need cookieauth. rpcpassword disabled cookie file auth.
        # Be careful if you copy the line below from the docker-compose.yml! A dollar sign is escaped.
        rpcauth=btcrpc:a6a5d29a3f44f02e4cd8cabb5b10a234$$ab6152915515f6a9cca806d2ab5f0e2794c346ba74f812c61e48241d523778b8
      HIDDENSERVICE_NAME: BTC-P2P,BTC-RPC
      BTC-P2P_HIDDENSERVICE_VIRTUAL_PORT: 8333
      BTC-P2P_HIDDENSERVICE_PORT: 39388
      BTC-RPC_HIDDENSERVICE_VIRTUAL_PORT: 8332
      BTC-RPC_HIDDENSERVICE_PORT: 43782
    expose:
    - "43782"
    - "39388"
    volumes:
    - "bitcoin_datadir:/data"
    - "bitcoin_wallet_datadir:/walletdata"
    - "tor_datadir:/home/tor/.tor"
    links:
    - tor
  nbxplorer:
    restart: unless-stopped
    container_name: generated_nbxplorer_1
    image: nicolasdorier/nbxplorer:2.5.25
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    links:
    - postgres
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "bitcoin_datadir:/root/.bitcoin"
  clightning_bitcoin:
    image: btcpayserver/lightning:v25.02
    container_name: btcpayserver_clightning_bitcoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      LIGHTNINGD_CHAIN: btc
      LIGHTNINGD_ALIAS: ${LIGHTNING_ALIAS}
      LIGHTNINGD_ANNOUNCEADDR: ${BTCPAY_ANNOUNCEABLE_HOST}
      LIGHTNINGD_PORT: 9735
      LIGHTNINGD_READY_FILE: /root/.nbxplorer/btc_fully_synched
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind
        experimental-offers
        database-upgrade=true
        rpc-file-mode=0666
        clnrest-port=3010
        clnrest-protocol=http
        clnrest-host=0.0.0.0
        grpc-port=9736

        proxy=tor:9050
      HIDDENSERVICE_NAME: c-lightning
      HIDDENSERVICE_PORT: 9735
      LIGHTNINGD_HIDDENSERVICE_HOSTNAME_FILE: /var/lib/tor/hidden_services/c-lightning/hostname
    volumes:
    - "clightning_bitcoin_datadir:/root/.lightning"
    - "bitcoin_datadir:/etc/bitcoin"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
    ports:
    - "9735:9735"
    - "3010"
    expose:
    - "9736"
    links:
    - bitcoind
    - tor
  bitcoin_rtl:
    image: shahanafarooqui/rtl:v0.15.4
    restart: unless-stopped
    environment:
      LN_IMPLEMENTATION: CLN
      CONFIG_PATH: /root/.lightning/config
      LN_SERVER_URL: http://clightning_bitcoin:3010
      RUNE_PATH: /root/.lightning/rune.env
      RTL_CONFIG_PATH: /data/
      BITCOIND_CONFIG_PATH: /etc/bitcoin/bitcoin.conf
      RTL_SSO: 1
      RTL_COOKIE_PATH: /data/.cookie
      LOGOUT_REDIRECT_LINK: /server/services
    labels:
      traefik.enable: "true"
      traefik.http.routers.bitcoin_rtl.rule: Host(`${BTCPAY_HOST}`) && (Path(`/rtl`) || PathPrefix(`/rtl/`))
    volumes:
    - "clightning_bitcoin_datadir:/root/.lightning"
    - "bitcoin_datadir:/etc/bitcoin"
    - "clightning_bitcoin_rtl_datadir:/data"
    expose:
    - "3000"
  tor:
    restart: unless-stopped
    image: btcpayserver/tor:0.4.8.10
    container_name: tor
    environment:
      TOR_PASSWORD: btcpayserver
      TOR_ADDITIONAL_CONFIG: /usr/local/etc/tor/torrc-2
      TOR_EXTRA_ARGS: |
        CookieAuthentication 1
    expose:
    - "9050"
    - "9051"
    volumes:
    - "tor_datadir:/home/tor/.tor"
    - "tor_torrcdir:/usr/local/etc/tor"
    - "tor_servicesdir:/var/lib/tor/hidden_services"
  tor-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.10.7
    container_name: tor-gen
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    - "./torrc.tmpl:/etc/docker-gen/templates/torrc.tmpl:ro"
    - "tor_torrcdir:/usr/local/etc/tor"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup tor -watch -wait 5s:30s /etc/docker-gen/templates/torrc.tmpl /usr/local/etc/tor/torrc-2
    links:
    - tor
  postgres:
    restart: unless-stopped
    container_name: generated_postgres_1
    shm_size: 256mb
    image: btcpayserver/postgres:13.18
    command: ["-c", "random_page_cost=1.0", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
volumes:
  btcpay_datadir: 
  btcpay_pluginsdir: 
  bitcoin_datadir: 
  bitcoin_wallet_datadir: 
  clightning_bitcoin_datadir: 
  clightning_bitcoin_rtl_datadir: 
  tor_datadir: 
  tor_torrcdir: 
  tor_servicesdir: 
  nbxplorer_datadir: 
  postgres_datadir: 
networks: {}
